# Requires Authorization=authId

query Profile {
    profile {
        id
        firstName
        lastName
        organization
        description
        cities {
            id
            title
        }
        activities {
            id
            title
        }
        social {
            id
            url
        }
        payments {
            id
            metadata
        }
        contacts {
            id
            metadata
        }
    }
}
