mutation UpdateProfile {
    updateProfile(
        input: {
            firstName: "Updated firstName",
            lastName: "Updated lastName",
            description: "Test Description Update",
            organization: "Test Organization",
            cityIds: ["cl0uci94o00016zpncsr8tmix"]
            activityIds: ["cl0uci94p00036zpneezlzs0f"]
            social: {
                create: [],
                delete: []
            }
            paymentOptions: {
                create: []
                delete: []
            }
            contacts: {
                create: []
                delete: []
            }
        }
    ) {
        id
        firstName
        lastName
        description
        organization
        cities {
            id
            title
        }
        activities {
            id
            title
        }
        social {
            id
            url
        }
        payments {
            id
            metadata
        }
        contacts {
            id
            metadata
        }
    }
}
