query VolunteerFilters {
    socialProviders {
        id
        title
    }
    activities {
        id
        title
    }
    paymentProviders {
        id
        title
    }
    contactProviders {
        id
        title
    }
    cities {
        id
        title
    }
}
