query VolunteerSearch {
    volunteersSearch(
        input: {
            cityIds: []
            activityIds: []
        }
    ) {
        id
        firstName
        lastName
        organization
        description
        cities {
            id
            title
        }
        activities {
            id
            title
        }
        social {
            id
            url
            provider {
                id
                title
            }
        }
        payments {
            id
            metadata
            provider {
                id
                title
            }
        }
        contacts {
            id
            metadata
            provider {
                id
                title
            }
        }
    }
}
