version: '3'

services:
  proxy:
    image: 'nginx:1.21.5'
    depends_on:
      - api-gateway
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  db:
    image: 'postgres:14'
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: volunteers
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api-gateway:
    image: 'ghcr.io/i-want-to-help-ukraine/api-gateway:release-RC_10052022'
    depends_on:
      - volunteer-service
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${GRAPHQL_SERVER_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
      AUTH_SERVICE_GRPC_NAME: ${AUTH_SERVICE_GRPC_NAME}
      AUTH_SERVICE_GRPC_PORT: ${AUTH_SERVICE_GRPC_PORT}
      BACKOFFICE_AUTH_SECRET: ${BACKOFFICE_AUTH_SECRET}
      FIREBASE_AUDIENCE: ${FIREBASE_AUDIENCE}
      FIREBASE_ISSUER: ${FIREBASE_ISSUER}
      FIREBASE_JWK_URI: ${FIREBASE_JWK_URI}
      PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
      PM2_SECRET_KEY: ${PM2_SECRET_KEY}
    command: >
      sh -c "cd /usr/src/app && pm2-runtime dist/src/main.js --name api-gateway"
    restart: on-failure

  volunteer-service:
    image: 'ghcr.io/i-want-to-help-ukraine/volunteer-service:release-RC_26042022'
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${VOLUNTEER_SERVICE_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${VOLUNTEER_SERVICE_DB_NAME}
      PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
      PM2_SECRET_KEY: ${PM2_SECRET_KEY}
    command: >
      sh -c "cd /usr/src/app && pm2-runtime dist/src/main.js --name volunteer-service"
    restart: on-failure

  auth-service:
    image: 'ghcr.io/i-want-to-help-ukraine/auth-service:release-RC_10052022'
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${AUTH_SERVICE_APP_PORT}
      AUTH_SERVICE_GRPC_NAME: ${AUTH_SERVICE_GRPC_NAME}
      AUTH_SERVICE_GRPC_PORT: ${AUTH_SERVICE_GRPC_PORT}
      BACKOFFICE_AUTH_SECRET: ${BACKOFFICE_AUTH_SECRET}
      DATABASE_URL: ${AUTH_DATABASE_URL}
    command: >
      sh -c "cd /usr/src/app && npm run start:prod"
    restart: on-failure

volumes:
  pgdata:
