version: '3'

services:
  proxy:
    image: 'nginx:1.21.5'
    depends_on:
      - api-gateway
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  website:
    image: 'ghcr.io/i-want-to-help-ukraine/i-want-to-help-ukraine-website:release-RC_25032022'
    depends_on:
      - api-gateway
    environment:
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_USER_AVATARS_PRESET_NAME: ${CLOUDINARY_USER_AVATARS_PRESET_NAME}
      CLOUDINARY_USER_AVATARS_FOLDER_NAME: ${CLOUDINARY_USER_AVATARS_FOLDER_NAME}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_API_URL: ${AUTH0_API_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      GRAPHQL_URL: ${GRAPHQL_URL}
      AUTH0_API_TOKEN: ${AUTH0_API_TOKEN}
      PORT: ${WEBSITE_PORT}
      HOST: ${WEBSITE_HOST}
    command: >
      sh -c "cd /usr/src/app && npm start"

  api-gateway:
    image: 'ghcr.io/i-want-to-help-ukraine/api-gateway:release-RC_20032022'
    depends_on:
      - volunteer-service
    environment:
      APP_PORT: ${GRAPHQL_SERVER_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
    command: >
      sh -c "cd /usr/src/app && pm2-runtime dist/main"
    restart: always

  volunteer-service:
    image: 'ghcr.io/i-want-to-help-ukraine/volunteer-service:release-20032022'
    environment:
      APP_PORT: ${VOLUNTEER_SERVICE_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${VOLUNTEER_SERVICE_DB_NAME}
    command: >
      sh -c "cd /usr/src/app && npx prisma migrate dev && pm2-runtime dist/main"
    restart: always
