version: '3'

services:
  proxy:
    image: 'nginx:1.21.5'
    depends_on:
      - api-gateway
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
      - '443:443'
    restart: always

  api-gateway:
    image: 'ghcr.io/i-want-to-help-ukraine/api-gateway:release-RC_20032022'
    depends_on:
      - volunteer-service
    environment:
      APP_PORT: ${GRAPHQL_SERVER_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
      AUTH0_DOMAIN: ${GQL_AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${GQL_AUTH0_AUDIENCE}
    command: >
      sh -c "cd /usr/src/app && pm2-runtime dist/src/main.js"
    restart: on-failure


  volunteer-service:
    image: 'ghcr.io/i-want-to-help-ukraine/volunteer-service:release-20032022'
    depends_on:
      - db
    environment:
      APP_PORT: ${VOLUNTEER_SERVICE_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${VOLUNTEER_SERVICE_DB_NAME}
    command: >
      sh -c "cd /usr/src/app && pm2-runtime dist/src/main.js"
    ports:
      - ${VOLUNTEER_SERVICE_APP_PORT}:${VOLUNTEER_SERVICE_APP_PORT}
    restart: on-failure
