version: '3'

services:
  proxy:
    image: 'nginx:1.21.5'
    depends_on:
      - api-gateway
    volumes:
      - './reverse-proxy/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    restart: always

  api-gateway:
    image: 'ghcr.io/i-want-to-help-ukraine/api-gateway:release-RC_30032022'
    depends_on:
      - volunteer-service
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${GRAPHQL_SERVER_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
      AUTH0_DOMAIN: ${GQL_AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${GQL_AUTH0_AUDIENCE}
      PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
      PM2_SECRET_KEY: ${PM2_SECRET_KEY}
    command: >
      sh -c "cd /usr/src/app && pm2-runtime dist/src/main.js --name api-gateway"
    restart: on-failure


  volunteer-service:
    image: 'ghcr.io/i-want-to-help-ukraine/volunteer-service:release-RC_30032022'
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${VOLUNTEER_SERVICE_APP_PORT}
      VOLUNTEER_SERVICE_GRPC_NAME: ${VOLUNTEER_SERVICE_GRPC_NAME}
      VOLUNTEER_SERVICE_GRPC_PORT: ${VOLUNTEER_SERVICE_GRPC_PORT}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${VOLUNTEER_SERVICE_DB_NAME}?sslmode=require
      PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
      PM2_SECRET_KEY: ${PM2_SECRET_KEY}
    command: >
      sh -c "cd /usr/src/app && pm2-runtime dist/src/main.js --name volunteer-service"
    restart: on-failure
